version: "3"

services:
  web:
    build: ../.
    image: djangoelk
    command: bash -c "python manage.py migrate && gunicorn --workers=2 --timeout 100 core.wsgi -b 0.0.0.0:8000 --reload --error-logfile '/djangoelk/logs/gunicorn-error.log'"
    ports:
      - 8000:8000
    volumes:
      - logs_volume:/djangoelk/logs

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web
  
  filebeat:
    image: filebeat:latest
    volumes:
      - logs_volume:/app/logs
    command: filebeat -c /etc/filebeat/filebeat.yml -e -d "*" -strict.perms=false
    depends_on:
      - web
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.0
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.1.0
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - 5000:5000
      - 5044:5044
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.1.0
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

volumes:
  logs_volume: